# AUTOGENERATED BY gen_vmi.py
# DO NOT EDIT!
from vmi_top_common import *

class VM_Load_Const(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "load"
        VM_Inst_With_Suff.__init__(self)


    def disasm(self, param):
        d = VM_Inst_With_Suff.disasm(self, param)
        d += " %s"%hex(param)
        return d

class VM_002(VM_Load_Const):
    def __init__(self):
        self.fn = "002.txt"
        self.size = 8
        VM_Load_Const.__init__(self)

class VM_003(VM_Load_Const):
    def __init__(self):
        self.fn = "003.txt"
        self.size = 16
        VM_Load_Const.__init__(self)

class VM_004(VM_Load_Const):
    def __init__(self):
        self.fn = "004.txt"
        self.size = 32
        VM_Load_Const.__init__(self)


class VM_Load_Addr(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "load"
        VM_Inst_With_Suff.__init__(self)


    def disasm(self, param):
        d = VM_Inst_With_Suff.disasm(self, param)
        d += " [addr]"
        return d

class VM_00a(VM_Load_Addr):
    def __init__(self):
        self.fn = "00a.txt"
        self.size = 8
        VM_Load_Addr.__init__(self)

class VM_00b(VM_Load_Addr):
    def __init__(self):
        self.fn = "00b.txt"
        self.size = 16
        VM_Load_Addr.__init__(self)

class VM_00c(VM_Load_Addr):
    def __init__(self):
        self.fn = "00c.txt"
        self.size = 32
        VM_Load_Addr.__init__(self)


class VM_Load_Reg(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "load"
        VM_Inst_With_Suff.__init__(self)


    def disasm(self, param):
        d = VM_Inst_With_Suff.disasm(self, param)
        d += " %s"%REG_DICT[param]
        return d

class VM_00e(VM_Load_Reg):
    def __init__(self):
        self.fn = "00e.txt"
        self.size = 8
        VM_Load_Reg.__init__(self)

class VM_00f(VM_Load_Reg):
    def __init__(self):
        self.fn = "00f.txt"
        self.size = 16
        VM_Load_Reg.__init__(self)

class VM_007(VM_Load_Reg):
    def __init__(self):
        self.fn = "007.txt"
        self.size = 32
        VM_Load_Reg.__init__(self)


class VM_Load_Ptr(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "load"
        VM_Inst_With_Suff.__init__(self)


    def disasm(self, param):
        d = VM_Inst_With_Suff.disasm(self, param)
        d += " [%s]"%hex(param)
        return d

class VM_011(VM_Load_Ptr):
    def __init__(self):
        self.fn = "011.txt"
        self.size = 8
        VM_Load_Ptr.__init__(self)

class VM_012(VM_Load_Ptr):
    def __init__(self):
        self.fn = "012.txt"
        self.size = 16
        VM_Load_Ptr.__init__(self)

class VM_20c(VM_Load_Ptr):
    def __init__(self):
        self.fn = "20c.txt"
        self.size = 32
        VM_Load_Ptr.__init__(self)


class VM_Store_Addr(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "store"
        VM_Inst_With_Suff.__init__(self)


    def disasm(self, param):
        d = VM_Inst_With_Suff.disasm(self, param)
        d += " [addr]"
        return d

class VM_016(VM_Store_Addr):
    def __init__(self):
        self.fn = "016.txt"
        self.size = 8
        VM_Store_Addr.__init__(self)

class VM_017(VM_Store_Addr):
    def __init__(self):
        self.fn = "017.txt"
        self.size = 16
        VM_Store_Addr.__init__(self)

class VM_018(VM_Store_Addr):
    def __init__(self):
        self.fn = "018.txt"
        self.size = 32
        VM_Store_Addr.__init__(self)


class VM_Store_Reg(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "store"
        VM_Inst_With_Suff.__init__(self)


    def disasm(self, param):
        d = VM_Inst_With_Suff.disasm(self, param)
        d += " %s"%REG_DICT[param]          
        return d

class VM_01a(VM_Store_Reg):
    def __init__(self):
        self.fn = "01a.txt"
        self.size = 8
        VM_Store_Reg.__init__(self)

class VM_01b(VM_Store_Reg):
    def __init__(self):
        self.fn = "01b.txt"
        self.size = 16
        VM_Store_Reg.__init__(self)

class VM_01c(VM_Store_Reg):
    def __init__(self):
        self.fn = "01c.txt"
        self.size = 32
        VM_Store_Reg.__init__(self)


class VM_Store_Ptr(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "store"
        VM_Inst_With_Suff.__init__(self)


    def disasm(self, param):
        d = VM_Inst_With_Suff.disasm(self, param)
        d += " [%s]"%hex(param)
        return d

class VM_01e(VM_Store_Ptr):
    def __init__(self):
        self.fn = "01e.txt"
        self.size = 8
        VM_Store_Ptr.__init__(self)

class VM_01f(VM_Store_Ptr):
    def __init__(self):
        self.fn = "01f.txt"
        self.size = 16
        VM_Store_Ptr.__init__(self)

class VM_020(VM_Store_Ptr):
    def __init__(self):
        self.fn = "020.txt"
        self.size = 32
        VM_Store_Ptr.__init__(self)


class VM_Add(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "add"
        VM_Inst_With_Suff.__init__(self)

class VM_022(VM_Add):
    def __init__(self):
        self.fn = "022.txt"
        self.size = 8
        VM_Add.__init__(self)

class VM_023(VM_Add):
    def __init__(self):
        self.fn = "023.txt"
        self.size = 16
        VM_Add.__init__(self)

class VM_024(VM_Add):
    def __init__(self):
        self.fn = "024.txt"
        self.size = 32
        VM_Add.__init__(self)


class VM_Sub(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "sub"
        VM_Inst_With_Suff.__init__(self)

class VM_027(VM_Sub):
    def __init__(self):
        self.fn = "027.txt"
        self.size = 8
        VM_Sub.__init__(self)

class VM_028(VM_Sub):
    def __init__(self):
        self.fn = "028.txt"
        self.size = 16
        VM_Sub.__init__(self)

class VM_029(VM_Sub):
    def __init__(self):
        self.fn = "029.txt"
        self.size = 32
        VM_Sub.__init__(self)


class VM_Imul2(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "imul2"
        VM_Inst_With_Suff.__init__(self)

class VM_02c(VM_Imul2):
    def __init__(self):
        self.fn = "02c.txt"
        self.size = 16
        VM_Imul2.__init__(self)

class VM_02d(VM_Imul2):
    def __init__(self):
        self.fn = "02d.txt"
        self.size = 32
        VM_Imul2.__init__(self)


class VM_Adc(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "adc"
        VM_Inst_With_Suff.__init__(self)

class VM_02f(VM_Adc):
    def __init__(self):
        self.fn = "02f.txt"
        self.size = 8
        VM_Adc.__init__(self)

class VM_030(VM_Adc):
    def __init__(self):
        self.fn = "030.txt"
        self.size = 16
        VM_Adc.__init__(self)

class VM_031(VM_Adc):
    def __init__(self):
        self.fn = "031.txt"
        self.size = 32
        VM_Adc.__init__(self)


class VM_And(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "and"
        VM_Inst_With_Suff.__init__(self)

class VM_033(VM_And):
    def __init__(self):
        self.fn = "033.txt"
        self.size = 8
        VM_And.__init__(self)

class VM_034(VM_And):
    def __init__(self):
        self.fn = "034.txt"
        self.size = 16
        VM_And.__init__(self)

class VM_035(VM_And):
    def __init__(self):
        self.fn = "035.txt"
        self.size = 32
        VM_And.__init__(self)


class VM_Cmp(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "cmp"
        VM_Inst_With_Suff.__init__(self)

class VM_037(VM_Cmp):
    def __init__(self):
        self.fn = "037.txt"
        self.size = 8
        VM_Cmp.__init__(self)

class VM_038(VM_Cmp):
    def __init__(self):
        self.fn = "038.txt"
        self.size = 16
        VM_Cmp.__init__(self)

class VM_039(VM_Cmp):
    def __init__(self):
        self.fn = "039.txt"
        self.size = 32
        VM_Cmp.__init__(self)


class VM_Xor(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "xor"
        VM_Inst_With_Suff.__init__(self)

class VM_03b(VM_Xor):
    def __init__(self):
        self.fn = "03b.txt"
        self.size = 8
        VM_Xor.__init__(self)

class VM_03c(VM_Xor):
    def __init__(self):
        self.fn = "03c.txt"
        self.size = 16
        VM_Xor.__init__(self)

class VM_03d(VM_Xor):
    def __init__(self):
        self.fn = "03d.txt"
        self.size = 32
        VM_Xor.__init__(self)


class VM_Or(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "or"
        VM_Inst_With_Suff.__init__(self)

class VM_03f(VM_Or):
    def __init__(self):
        self.fn = "03f.txt"
        self.size = 8
        VM_Or.__init__(self)

class VM_040(VM_Or):
    def __init__(self):
        self.fn = "040.txt"
        self.size = 16
        VM_Or.__init__(self)

class VM_041(VM_Or):
    def __init__(self):
        self.fn = "041.txt"
        self.size = 32
        VM_Or.__init__(self)


class VM_Test(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "test"
        VM_Inst_With_Suff.__init__(self)

class VM_043(VM_Test):
    def __init__(self):
        self.fn = "043.txt"
        self.size = 8
        VM_Test.__init__(self)

class VM_044(VM_Test):
    def __init__(self):
        self.fn = "044.txt"
        self.size = 16
        VM_Test.__init__(self)

class VM_045(VM_Test):
    def __init__(self):
        self.fn = "045.txt"
        self.size = 32
        VM_Test.__init__(self)


class VM_Inc(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "inc"
        VM_Inst_With_Suff.__init__(self)

class VM_053(VM_Inc):
    def __init__(self):
        self.fn = "053.txt"
        self.size = 8
        VM_Inc.__init__(self)

class VM_054(VM_Inc):
    def __init__(self):
        self.fn = "054.txt"
        self.size = 16
        VM_Inc.__init__(self)

class VM_055(VM_Inc):
    def __init__(self):
        self.fn = "055.txt"
        self.size = 32
        VM_Inc.__init__(self)


class VM_Rcl(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "rcl"
        VM_Inst_With_Suff.__init__(self)

class VM_057(VM_Rcl):
    def __init__(self):
        self.fn = "057.txt"
        self.size = 8
        VM_Rcl.__init__(self)

class VM_058(VM_Rcl):
    def __init__(self):
        self.fn = "058.txt"
        self.size = 16
        VM_Rcl.__init__(self)

class VM_059(VM_Rcl):
    def __init__(self):
        self.fn = "059.txt"
        self.size = 32
        VM_Rcl.__init__(self)


class VM_Rcr(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "rcr"
        VM_Inst_With_Suff.__init__(self)

class VM_05b(VM_Rcr):
    def __init__(self):
        self.fn = "05b.txt"
        self.size = 8
        VM_Rcr.__init__(self)

class VM_05c(VM_Rcr):
    def __init__(self):
        self.fn = "05c.txt"
        self.size = 16
        VM_Rcr.__init__(self)

class VM_05d(VM_Rcr):
    def __init__(self):
        self.fn = "05d.txt"
        self.size = 32
        VM_Rcr.__init__(self)


class VM_Rol(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "rol"
        VM_Inst_With_Suff.__init__(self)

class VM_05f(VM_Rol):
    def __init__(self):
        self.fn = "05f.txt"
        self.size = 8
        VM_Rol.__init__(self)

class VM_060(VM_Rol):
    def __init__(self):
        self.fn = "060.txt"
        self.size = 16
        VM_Rol.__init__(self)

class VM_061(VM_Rol):
    def __init__(self):
        self.fn = "061.txt"
        self.size = 32
        VM_Rol.__init__(self)


class VM_Ror(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "ror"
        VM_Inst_With_Suff.__init__(self)

class VM_063(VM_Ror):
    def __init__(self):
        self.fn = "063.txt"
        self.size = 8
        VM_Ror.__init__(self)

class VM_064(VM_Ror):
    def __init__(self):
        self.fn = "064.txt"
        self.size = 16
        VM_Ror.__init__(self)

class VM_065(VM_Ror):
    def __init__(self):
        self.fn = "065.txt"
        self.size = 32
        VM_Ror.__init__(self)


class VM_Sar(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "sar"
        VM_Inst_With_Suff.__init__(self)

class VM_06b(VM_Sar):
    def __init__(self):
        self.fn = "06b.txt"
        self.size = 8
        VM_Sar.__init__(self)

class VM_06c(VM_Sar):
    def __init__(self):
        self.fn = "06c.txt"
        self.size = 16
        VM_Sar.__init__(self)

class VM_06d(VM_Sar):
    def __init__(self):
        self.fn = "06d.txt"
        self.size = 32
        VM_Sar.__init__(self)


class VM_Shl(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "shl"
        VM_Inst_With_Suff.__init__(self)

class VM_067(VM_Shl):
    def __init__(self):
        self.fn = "067.txt"
        self.size = 8
        VM_Shl.__init__(self)

class VM_068(VM_Shl):
    def __init__(self):
        self.fn = "068.txt"
        self.size = 16
        VM_Shl.__init__(self)

class VM_069(VM_Shl):
    def __init__(self):
        self.fn = "069.txt"
        self.size = 32
        VM_Shl.__init__(self)


class VM_Shr(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "shr"
        VM_Inst_With_Suff.__init__(self)

class VM_073(VM_Shr):
    def __init__(self):
        self.fn = "073.txt"
        self.size = 8
        VM_Shr.__init__(self)

class VM_074(VM_Shr):
    def __init__(self):
        self.fn = "074.txt"
        self.size = 16
        VM_Shr.__init__(self)

class VM_075(VM_Shr):
    def __init__(self):
        self.fn = "075.txt"
        self.size = 32
        VM_Shr.__init__(self)


class VM_Dec(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "dec"
        VM_Inst_With_Suff.__init__(self)

class VM_077(VM_Dec):
    def __init__(self):
        self.fn = "077.txt"
        self.size = 8
        VM_Dec.__init__(self)

class VM_078(VM_Dec):
    def __init__(self):
        self.fn = "078.txt"
        self.size = 16
        VM_Dec.__init__(self)

class VM_079(VM_Dec):
    def __init__(self):
        self.fn = "079.txt"
        self.size = 32
        VM_Dec.__init__(self)


class VM_Bt(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "bt"
        VM_Inst_With_Suff.__init__(self)

class VM_0a8(VM_Bt):
    def __init__(self):
        self.fn = "0a8.txt"
        self.size = 16
        VM_Bt.__init__(self)

class VM_0a9(VM_Bt):
    def __init__(self):
        self.fn = "0a9.txt"
        self.size = 32
        VM_Bt.__init__(self)


class VM_Btc(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "btc"
        VM_Inst_With_Suff.__init__(self)

class VM_0ab(VM_Btc):
    def __init__(self):
        self.fn = "0ab.txt"
        self.size = 16
        VM_Btc.__init__(self)

class VM_0ac(VM_Btc):
    def __init__(self):
        self.fn = "0ac.txt"
        self.size = 32
        VM_Btc.__init__(self)


class VM_Btr(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "btr"
        VM_Inst_With_Suff.__init__(self)

class VM_0af(VM_Btr):
    def __init__(self):
        self.fn = "0af.txt"
        self.size = 16
        VM_Btr.__init__(self)

class VM_0b0(VM_Btr):
    def __init__(self):
        self.fn = "0b0.txt"
        self.size = 32
        VM_Btr.__init__(self)


class VM_Bts(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "bts"
        VM_Inst_With_Suff.__init__(self)

class VM_0b3(VM_Bts):
    def __init__(self):
        self.fn = "0b3.txt"
        self.size = 16
        VM_Bts.__init__(self)

class VM_0b4(VM_Bts):
    def __init__(self):
        self.fn = "0b4.txt"
        self.size = 32
        VM_Bts.__init__(self)


class VM_Sbb(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "sbb"
        VM_Inst_With_Suff.__init__(self)

class VM_0b7(VM_Sbb):
    def __init__(self):
        self.fn = "0b7.txt"
        self.size = 8
        VM_Sbb.__init__(self)

class VM_0b8(VM_Sbb):
    def __init__(self):
        self.fn = "0b8.txt"
        self.size = 16
        VM_Sbb.__init__(self)

class VM_0b9(VM_Sbb):
    def __init__(self):
        self.fn = "0b9.txt"
        self.size = 32
        VM_Sbb.__init__(self)


class VM_Mul(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "mul"
        VM_Inst_With_Suff.__init__(self)

class VM_0bb(VM_Mul):
    def __init__(self):
        self.fn = "0bb.txt"
        self.size = 8
        VM_Mul.__init__(self)

class VM_0bc(VM_Mul):
    def __init__(self):
        self.fn = "0bc.txt"
        self.size = 16
        VM_Mul.__init__(self)

class VM_0bd(VM_Mul):
    def __init__(self):
        self.fn = "0bd.txt"
        self.size = 32
        VM_Mul.__init__(self)


class VM_Imul1(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "imul1"
        VM_Inst_With_Suff.__init__(self)

class VM_0bf(VM_Imul1):
    def __init__(self):
        self.fn = "0bf.txt"
        self.size = 8
        VM_Imul1.__init__(self)

class VM_0c0(VM_Imul1):
    def __init__(self):
        self.fn = "0c0.txt"
        self.size = 16
        VM_Imul1.__init__(self)

class VM_0c1(VM_Imul1):
    def __init__(self):
        self.fn = "0c1.txt"
        self.size = 32
        VM_Imul1.__init__(self)


class VM_Div(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "div"
        VM_Inst_With_Suff.__init__(self)

class VM_0c3(VM_Div):
    def __init__(self):
        self.fn = "0c3.txt"
        self.size = 8
        VM_Div.__init__(self)

class VM_0c4(VM_Div):
    def __init__(self):
        self.fn = "0c4.txt"
        self.size = 16
        VM_Div.__init__(self)

class VM_0c5(VM_Div):
    def __init__(self):
        self.fn = "0c5.txt"
        self.size = 32
        VM_Div.__init__(self)


class VM_Idiv(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "idiv"
        VM_Inst_With_Suff.__init__(self)

class VM_0c7(VM_Idiv):
    def __init__(self):
        self.fn = "0c7.txt"
        self.size = 8
        VM_Idiv.__init__(self)

class VM_0c8(VM_Idiv):
    def __init__(self):
        self.fn = "0c8.txt"
        self.size = 16
        VM_Idiv.__init__(self)

class VM_0c9(VM_Idiv):
    def __init__(self):
        self.fn = "0c9.txt"
        self.size = 32
        VM_Idiv.__init__(self)


class VM_Neg(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "neg"
        VM_Inst_With_Suff.__init__(self)

class VM_0cf(VM_Neg):
    def __init__(self):
        self.fn = "0cf.txt"
        self.size = 8
        VM_Neg.__init__(self)

class VM_0d0(VM_Neg):
    def __init__(self):
        self.fn = "0d0.txt"
        self.size = 16
        VM_Neg.__init__(self)

class VM_0d1(VM_Neg):
    def __init__(self):
        self.fn = "0d1.txt"
        self.size = 32
        VM_Neg.__init__(self)


class VM_Not(VM_Inst_With_Suff):
    def __init__(self):
        self.mnem = "not"
        VM_Inst_With_Suff.__init__(self)

class VM_0d3(VM_Not):
    def __init__(self):
        self.fn = "0d3.txt"
        self.size = 8
        VM_Not.__init__(self)

class VM_0d4(VM_Not):
    def __init__(self):
        self.fn = "0d4.txt"
        self.size = 16
        VM_Not.__init__(self)

class VM_0d5(VM_Not):
    def __init__(self):
        self.fn = "0d5.txt"
        self.size = 32
        VM_Not.__init__(self)

